networks:
  internal_network:
    name: 'web3signer_hashicorp_tls_network'
    # NOT external - created by this compose file

services:
  vault-ssl-certificate:
    image: alpine:latest
    container_name: 'ws-vault-ssl-certificate'
    environment:
      - TRUSTSTORE_PASSWORD=${TRUSTSTORE_PASSWORD:-test123}
    command: sh -c /scripts/gen-cert.sh
    volumes:
      - ./certs:/certs
      - ./scripts:/scripts
      - ../web3signer/config:/web3signer/config
    healthcheck:
      test: [ "CMD-SHELL", "[ -f /certs/server.crt ] && [ -f /web3signer/config/knownhosts ]" ]
      interval: 5s
      timeout: 3s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
    networks:
      - internal_network
  
  vault:
    image: hashicorp/vault:latest
    container_name: 'ws-vault-tls'
    command: ["server", "-config=/config/vault-server.hcl", "-log-level=debug"]
    ports:
      - "8200:8200"
    volumes:
      - "./certs:/tls"
      - "./data:/data"
      - "./config:/config"
    environment:
      - 'VAULT_SKIP_VERIFY=true'
      - 'VAULT_ENABLE_FILE_PERMISSIONS_CHECK=false'
    healthcheck:
      test: ["CMD-SHELL", "curl -k --fail https://localhost:8200/v1/sys/health?sealedcode=200&uninitcode=200"]
      interval: 3s
      retries: 3
    cap_add:
      - IPC_LOCK
    depends_on:
      vault-ssl-certificate:
        condition: service_completed_successfully
    networks:
      - internal_network

  init-vault:
    build:
      context: ./initvault
    container_name: "ws-vault-init"
    volumes:
      - ./creds:/creds
    depends_on:
      vault:
        condition: service_healthy
    command: https://vault:8200
    networks:
      - internal_network

  vault-proxy:
    profiles: [ "vault-proxy" ]
    image: hashicorp/vault:latest
    container_name: 'ws-vault-proxy'
    command: ["proxy", "-config=/config/vault-proxy-config.hcl", "-log-level=debug"]
    volumes:
      - ./config:/config
      - ./creds:/creds
      - ./vault-proxy-pid:/run/vault-proxy
    environment:
      - 'VAULT_SKIP_VERIFY=true'
      - 'VAULT_ENABLE_FILE_PERMISSIONS_CHECK=false'
      - 'VAULT_ADDR=https://vault:8200'
    cap_add:
      - IPC_LOCK
    depends_on:
      init-vault:
        condition: service_completed_successfully
    networks:
      - internal_network
