{
 "title": "Web3Signer Overview",
 "description": "Web3signer Eth2 Dashboard https://github.com/ConsenSys/web3signer",
 "tags": [
  "ethereum",
  "web3signer",
  "eth2.0"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "system", "query": { "query": "signing_signers_loaded_count" } },
   { "name": "job", "query": { "query": "signing_signers_loaded_count" } }
  ]
 },
 "panels": [
  {
   "title": "Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Release version",
   "type": "stat",
   "description": "Release version data",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_release{job=\"web3signer-node\",instance=~\"$system\"}"
    }
   ]
  },
  {
   "title": "Loaded keys",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "signing_signers_loaded_count{instance=~\"$system\"}"
    }
   ]
  },
  {
   "title": "Max heap",
   "type": "stat",
   "description": "The maximum heap setting of the node's JVM.",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jvm_memory_max_bytes{area=\"heap\", instance=~\"$system\", job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Malformed Signing Requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_bls_malformed_request_count_total{instance=~\"$system\"}"
    }
   ]
  },
  {
   "title": "Slashing protection prevented Signings",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eth2_slashingprotection_prevented_signings_total{instance=~\"$system\"}"
    }
   ]
  },
  {
   "title": "Signings for unknown validators/s",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "signing_bls_missing_identifier_count_total{instance=~\"$system\"}"
    }
   ]
  },
  {
   "title": "Signing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Signing Time",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "signing_bls_signing_duration{instance=~\"$system\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Signatures/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(signing_bls_signing_duration_count{instance=~\"$system\"}[1m]))",
     "legendFormat": "sigs/s"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "Number of CPU cores in use.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{instance=~\"$system\", job=\"$job\"}[1m])",
     "legendFormat": "CPU Time IRate [{{instance}}]"
    }
   ]
  },
  {
   "title": "JVM Heap Space",
   "type": "graph",
   "description": "Total amount of heap memory in use, and the amount allocated.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=~\"$system\", area=\"heap\", job=\"$job\"} + ignoring(area) jvm_memory_used_bytes{instance=~\"$system\", area=\"nonheap\"}",
     "legendFormat": "Heap used  [{{instance}}]"
    },
    {
     "expr": "jvm_memory_max_bytes{instance=~\"$system\", area=\"heap\", job=\"$job\"} + ignoring(area) jvm_memory_max_bytes{instance=~\"$system\", area=\"nonheap\"}",
     "legendFormat": "Max heap [{{instance}}]"
    }
   ]
  },
  {
   "title": "Process memory",
   "type": "graph",
   "description": "The total system memory used by the process, otherwise known as the resident set size (RSS).",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$system\", job=\"$job\"}",
     "legendFormat": "RSS [{{instance}}]"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "graph",
   "description": "Percentage of time spent in garbage collection, young and old generation.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{instance=~\"$system\", job=\"$job\"}[1m])",
     "legendFormat": "{{gc}} [{{instance}}]"
    }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "graph",
   "description": "Threads allocated by the JVM.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_state{state=\"WAITING\",instance=~\"$system\", job=\"$job\"}",
     "legendFormat": "{{state}} [{{instance}}]"
    },
    {
     "expr": "jvm_threads_state{state=\"TIMED_WAITING\",instance=~\"$system\", job=\"$job\"}",
     "legendFormat": "{{state}} [{{instance}}]"
    },
    {
     "expr": "jvm_threads_state{state=\"RUNNABLE\",instance=~\"$system\", job=\"$job\"}",
     "legendFormat": "{{state}} [{{instance}}]"
    },
    {
     "expr": "jvm_threads_state{state=\"BLOCKED\",instance=~\"$system\", job=\"$job\"}",
     "legendFormat": "{{state}} [{{instance}}]"
    },
    {
     "expr": "jvm_threads_state{state=\"NEW\",instance=~\"$system\", job=\"$job\"}",
     "legendFormat": "{{state}} [{{instance}}]"
    },
    {
     "expr": "jvm_threads_state{state=\"TERMINATED\",instance=~\"$system\", job=\"$job\"}",
     "legendFormat": "{{state}} [{{instance}}]"
    }
   ]
  }
 ]
}