http-listen-host: "0.0.0.0"
http-listen-port: 9000
http-host-allowlist: "*"

metrics-enabled: true
metrics-host: "0.0.0.0"
metrics-port: 9001
metrics-host-allowlist: "*"

logging: "INFO"

# Load Web3Signer Hashicorp Vault configuration
key-store-path: /var/config/keys

# eth2 subcommand options
eth2.slashing-protection-enabled: true
eth2.slashing-protection-db-username: postgres
eth2.slashing-protection-db-password: postgres
eth2.slashing-protection-db-url: "jdbc:postgresql://db/web3signer"
# eth2 BLS keystores bulk loading
eth2.keystores-path: "/var/config/keystores"
eth2.keystores-password-file: "/var/config/keystores/passwords.txt"

