networks:
  internal_network:
    name: '${INTERNAL_NETWORK_NAME:-web3signer_hashicorp_tls_network}'
    external: true

services:
  web3signer:
    image: consensys/web3signer:develop
    container_name: 'ws-develop'
    command: --config-file=/var/config/config.yaml eth2
    volumes:
      - ./config:/var/config
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - internal_network