version: '3.8'

networks:
  internal_network:
    name: '${INTERNAL_NETWORK_NAME:-web3signer_hashicorp_tls_network}'
    external: true

services:
  knownhosts-copier:
    image: alpine:latest
    container_name: 'ws-knownhosts-copier'
    command: >
      sh -c "test -f /source-certs/knownhosts && 
      cp /source-certs/knownhosts /target-config/ && 
      chown 1000:1000 /target-config/knownhosts || 
      (echo 'Error: knownhosts file not found'; exit 1)"
    volumes:
      - ../vault/certs:/source-certs:ro
      - ./config:/target-config
    networks:
      - internal_network
    restart: "no"

  web3signer:
    image: consensys/web3signer:develop
    container_name: 'ws-develop'
    depends_on:
      knownhosts-copier:
        condition: service_completed_successfully
    command: --config-file=/var/config/config.yaml eth2
    volumes:
      - ./config:/var/config
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - internal_network