services:
  bls_keys_gen:
    image: '${IMAGE_NAME}'
    container_name: 'bls_keys_gen'
    command:
      - keystores
      - --output
      - /var/config/keys
      - --count
      - "${KEYS_COUNT:-50}"
    volumes:
      - ../web3signer/config/keys:/var/config/keys

# Network definition
networks:
  internal_network:
    name: '${INTERNAL_NETWORK_NAME:-w3s_network}'
    external: true  # Manually created network for internal communication