services:
  bls_keys_gen:
    image: usmans/w3s-conf-gen:3.0.0
    container_name: 'bls_keys_gen'
    command:
      - keystores
      - --output
      - /var/config/keystores
      - --count
      - "${KEYS_COUNT:-50}"
      - --no-generate-config
    volumes:
      - ../web3signer/config/keystores:/var/config/keystores

# Network definition
networks:
  internal_network:
    name: '${INTERNAL_NETWORK_NAME:-w3s_network}'
    external: true  # Manually created network for internal communication